/* MTI_DPI */

/*
 * Copyright 2002-2016 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'win64'
 */
#ifndef INCLUDED_TASK_1
#define INCLUDED_TASK_1

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"



DPI_LINK_DECL DPI_DLLESPEC
int
create_mem(
    int depth);

DPI_LINK_DECL DPI_DLLESPEC
int
read_word_c(
    int addr,
    int* data);

DPI_LINK_DECL DPI_DLLESPEC
int
write_word_c(
    int addr,
    int data);

#endif 
